apiVersion: v1
kind: ConfigMap
metadata:
  name: forex-alert-backend-configmap
  namespace: ${FOREX_ALERT_NAMESPACE}
data:
  NODE_ENV: ${FOREX_ALERT_NODE_ENV}
  PRIVATE_KEY: 'n@e#w$f%a^r&m*m(e)m_o+r1i2z3e4567890'
  MONGO_URI: ${FOREX_ALERT_MONGO_URI}
  COOKIE_SECURE: 'true'
  JOB_TIME: '2000'
  REDIS_HOST: forex-alert-redis-service
  REDIS_PORT: '6379'
  LIMIT_ALERT_QUEUE: '100'
